apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: girogopos
  name: girogopos
spec:
  containers:
  - image: nginx
    name: girogopos
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
