apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    pvc: meu-primeiro-pvc
  name: meupvc
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: giropops
  selector:  
    matchLabels: 
      storage: lento
  accessModes:
    - ReadWriteOnce

