apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deployment
  strategy: {}
  template: # Config do POD
    metadata:
      labels:
        app: nginx-deployment
    spec: 
      containers:
        - image: nginx
          name: nginx-container
          resources: 
            limits:
              cpu: "0.5"
              memory: 256Mi
            requests:
              cpu: "0.3"
              memory: 64Mi
          readinessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:80/
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

    
