apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
  namespace: giropops
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-deployment
  strategy: 
    type: RollingUpdate # Outra alternativa: Reacreate - faz altearacao em todos de uma so vez
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 25%
  template: # Config do POD
    metadata:
      labels:
        app: nginx-deployment
    spec: 
      containers:
        - image: nginx:1.15.0
          name: nginx-container
          resources: 
            limits:
              cpu: "0.5"
              memory: 256Mi
            requests:
              cpu: "0.3"
              memory: 64Mi

    
