apiVersion: v1
kind: Pod
metadata:
  labels:
    run: girus
    service: webserver
  name: girus
spec:
  containers:
  - image: busybox 
    name: busybox
    args:
    - sleep
    - "600"
    resources:
      limits:
        cpu: "0.5" ## Maximo do uso de cpu
        memory: "128Mi"
      requests:
        cpu: "0.3" ## Garante o uso de 0.3 cpu (minimo que sera usado)
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
